# Generated by Django 3.0.5 on 2020-08-07 10:18

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('profilePicture', models.FileField(blank=True, null=True, upload_to='')),
                ('roles', models.CharField(default='driver', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('profilePicture', models.FileField(blank=True, null=True, upload_to='')),
                ('roles', models.CharField(default='manager', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('profilePicture', models.FileField(blank=True, null=True, upload_to='')),
                ('roles', models.CharField(default='passenger', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zoneName', models.CharField(max_length=255, unique=True)),
                ('routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeGo.Route')),
            ],
            options={
                'unique_together': {('routes', 'zoneName')},
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('departureCity', models.CharField(blank=True, max_length=255)),
                ('departureLocation', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('destinationCity', models.CharField(blank=True, max_length=255)),
                ('destinationLocation', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('numberOfSeets', models.PositiveIntegerField(null=True)),
                ('disabledPoeple', models.PositiveIntegerField(null=True)),
                ('passengers', models.ManyToManyField(blank=True, to='WeGo.Passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plateNumber', models.CharField(max_length=11, unique=True)),
                ('available', models.BooleanField(choices=[('True', 'True'), ('False', 'False')])),
                ('issuingDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeGo.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('busStopName', models.CharField(max_length=100, unique=True)),
                ('zones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeGo.Zone')),
            ],
            options={
                'unique_together': {('zones', 'busStopName')},
            },
        ),
    ]
