# Generated by Django 3.0.5 on 2020-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeGo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('departureCity', models.CharField(max_length=255)),
                ('destinationCity', models.CharField(max_length=255)),
                ('passengers', models.ManyToManyField(blank=True, to='WeGo.Passenger')),
            ],
        ),
    ]
