# Generated by Django 3.0.5 on 2020-07-26 15:26

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('WeGo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='departureLocation',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='destinationLocation',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
