# Generated by Django 3.0.3 on 2020-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeGo', '0002_auto_20200726_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='telephone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='departureCity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='destinationCity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='numberOfSeets',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
