# Generated by Django 3.0.3 on 2020-08-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeGo', '0003_auto_20200730_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
