# Generated by Django 3.0.3 on 2020-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondemandUssd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdriderequest',
            name='pickupTime',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
