# Generated by Django 3.0.3 on 2020-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondemandUssd', '0002_auto_20200804_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdriderequest',
            name='pickupTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
